#!/usr/bin/env node
/*
 * Generates the 20 TET Mock Test data files (assets/data/test-N.js) and their
 * thin HTML shells (tet-mock-test-N.html) from the shared question bank in
 * scripts/question-bank.js.
 *
 * Each bank (cdp/en/hi/math/evs) holds 60 questions. For test N, a 30-question
 * window is sliced out starting at offset ((N-1) * 7) % 60 (wrapping around),
 * so every test gets a full, non-repeating 30-question section and the offset
 * pattern spreads the 20 tests across the whole bank. Test 1 always starts at
 * offset 0, which reproduces the original hand-written test 1 exactly.
 *
 * To add test 21+: add more questions to scripts/question-bank.js (append to
 * the relevant array, keep it a multiple that divides evenly if possible),
 * bump TOTAL_TESTS below, and re-run: node scripts/generate-tests.js
 */
const fs = require('fs');
const path = require('path');
const bank = require('./question-bank.js');

const TOTAL_TESTS = 20;
const QUESTIONS_PER_SECTION = 30;
const OFFSET_STEP = 7;

const ROOT = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'assets', 'data');

const SECTION_DEFS = [
  { name: 'Child Development & Pedagogy', mode: 'bilingual', bank: 'cdp' },
  { name: 'Language-1 (English)', mode: 'en', bank: 'en' },
  { name: 'Language-2 (Hindi)', mode: 'hi', bank: 'hi' },
  { name: 'Mathematics', mode: 'bilingual', bank: 'math' },
  { name: 'Environmental Studies', mode: 'bilingual', bank: 'evs' },
];

function sliceWindow(arr, offset, count) {
  const out = [];
  for (let i = 0; i < count; i++) {
    out.push(arr[(offset + i) % arr.length]);
  }
  return out;
}

function serializeQuestion(q) {
  const parts = [];
  if (q.en) parts.push(`en:{q:${JSON.stringify(q.en.q)}, options:${JSON.stringify(q.en.options)}}`);
  if (q.hi) parts.push(`hi:{q:${JSON.stringify(q.hi.q)}, options:${JSON.stringify(q.hi.options)}}`);
  parts.push(`answer:${q.answer}`);
  return `      {${parts.join(', ')}}`;
}

function buildDataFile(testId) {
  const lines = [];
  lines.push('// Auto-generated by scripts/generate-tests.js — do not edit by hand.');
  lines.push('// Regenerate with: node scripts/generate-tests.js');
  lines.push(`// Pattern: Child Development & Pedagogy | Language-1 (English) | Language-2 (Hindi) | Mathematics | EVS`);
  lines.push('// 30 questions per section x 5 sections = 150 questions total, 1 mark each, no negative marking.');
  lines.push('const sections = [');
  SECTION_DEFS.forEach((def, idx) => {
    const bankArr = bank[def.bank];
    const secOffset = ((testId - 1) * OFFSET_STEP) % bankArr.length;
    const questions = sliceWindow(bankArr, secOffset, QUESTIONS_PER_SECTION);
    lines.push('  {');
    lines.push(`    name: ${JSON.stringify(def.name)},`);
    lines.push(`    mode: ${JSON.stringify(def.mode)},`);
    lines.push('    questions: [');
    lines.push(questions.map(serializeQuestion).join(',\n'));
    lines.push('    ]');
    lines.push(idx === SECTION_DEFS.length - 1 ? '  }' : '  },');
  });
  lines.push('];');
  lines.push('');
  return lines.join('\n');
}

const HTML_TEMPLATE = fs.readFileSync(path.join(__dirname, 'test-page.template.html'), 'utf8');

function buildHtmlFile(testId) {
  return HTML_TEMPLATE.replace(/__TEST_ID__/g, String(testId));
}

fs.mkdirSync(DATA_DIR, { recursive: true });

for (let testId = 1; testId <= TOTAL_TESTS; testId++) {
  fs.writeFileSync(path.join(DATA_DIR, `test-${testId}.js`), buildDataFile(testId));
  fs.writeFileSync(path.join(ROOT, `tet-mock-test-${testId}.html`), buildHtmlFile(testId));
}

console.log(`Generated ${TOTAL_TESTS} test data files in ${DATA_DIR} and ${TOTAL_TESTS} HTML pages in ${ROOT}.`);
