import { MonitoringStation } from '../types/hydrology';

export const CWC_SONE_STATIONS: MonitoringStation[] = [
  {
    id: 'station-rewa',
    name: 'Rewa Division (Sone River)',
    hindiName: 'रीवा प्रभाग (सोन नदी)',
    river: 'Sone River',
    division: 'Rewa Division',
    district: 'Rewa / Sidhi',
    state: 'Madhya Pradesh',
    coordinates: {
      lat: 24.485,
      lng: 82.084,
    },
    warningLevel: 323.50,
    dangerLevel: 325.00,
    highestFloodLevel: 327.40,
    highestFloodDate: '2016-08-20',
    gaugeDatum: 310.00,
    cwcStationCode: 'CWC-SON-REW',
  },
  {
    id: 'station-dehri',
    name: 'Dehri-on-Sone',
    hindiName: 'डेहरी ऑन सोन',
    river: 'Sone River',
    division: 'Patna Division',
    district: 'Rohtas',
    state: 'Bihar',
    coordinates: {
      lat: 24.908,
      lng: 84.184,
    },
    warningLevel: 103.00,
    dangerLevel: 104.50,
    highestFloodLevel: 105.82,
    highestFloodDate: '1975-08-25',
    gaugeDatum: 95.00,
    cwcStationCode: 'CWC-SON-DHR',
  },
  {
    id: 'station-indrapuri',
    name: 'Indrapuri Barrage',
    hindiName: 'इंद्रपुरी बैराज',
    river: 'Sone River',
    division: 'Patna Division',
    district: 'Rohtas / Aurangabad',
    state: 'Bihar',
    coordinates: {
      lat: 24.845,
      lng: 84.032,
    },
    warningLevel: 107.50,
    dangerLevel: 109.00,
    highestFloodLevel: 110.45,
    highestFloodDate: '2001-09-12',
    gaugeDatum: 98.00,
    cwcStationCode: 'CWC-SON-IND',
  },
  {
    id: 'station-koelwar',
    name: 'Koelwar Bridge',
    hindiName: 'कोईलवर पुल',
    river: 'Sone River',
    division: 'Patna Division',
    district: 'Bhojpur / Patna',
    state: 'Bihar',
    coordinates: {
      lat: 25.568,
      lng: 84.731,
    },
    warningLevel: 52.50,
    dangerLevel: 53.30,
    highestFloodLevel: 55.45,
    highestFloodDate: '2016-08-24',
    gaugeDatum: 45.00,
    cwcStationCode: 'CWC-SON-KLW',
  },
  {
    id: 'station-chopan',
    name: 'Chopan (Sonbhadra)',
    hindiName: 'चोपन (सोनभद्र)',
    river: 'Sone River',
    division: 'Mirzapur Division',
    district: 'Sonbhadra',
    state: 'Uttar Pradesh',
    coordinates: {
      lat: 24.524,
      lng: 83.025,
    },
    warningLevel: 165.50,
    dangerLevel: 167.00,
    highestFloodLevel: 169.50,
    highestFloodDate: '1998-08-29',
    gaugeDatum: 155.00,
    cwcStationCode: 'CWC-SON-CPN',
  },
  {
    id: 'station-bansagar',
    name: 'Bansagar Dam (Reservoir)',
    hindiName: 'बाणसागर बांध',
    river: 'Sone River',
    division: 'Shahdol Division',
    district: 'Shahdol',
    state: 'Madhya Pradesh',
    coordinates: {
      lat: 24.167,
      lng: 81.294,
    },
    warningLevel: 340.50,
    dangerLevel: 341.64,
    highestFloodLevel: 342.90,
    highestFloodDate: '2016-08-19',
    gaugeDatum: 300.00,
    cwcStationCode: 'CWC-SON-BSG',
  },
  {
    id: 'station-daudnagar',
    name: 'Daudnagar',
    hindiName: 'दाउदनगर',
    river: 'Sone River',
    division: 'Magadh Division',
    district: 'Aurangabad',
    state: 'Bihar',
    coordinates: {
      lat: 25.112,
      lng: 84.312,
    },
    warningLevel: 75.20,
    dangerLevel: 76.50,
    highestFloodLevel: 78.10,
    highestFloodDate: '2016-08-22',
    gaugeDatum: 68.00,
    cwcStationCode: 'CWC-SON-DNR',
  },
  {
    id: 'station-maner',
    name: 'Maner (Ganga Confluence)',
    hindiName: 'मनेर (गंगा संगम)',
    river: 'Sone River',
    division: 'Patna Division',
    district: 'Patna',
    state: 'Bihar',
    coordinates: {
      lat: 25.688,
      lng: 84.885,
    },
    warningLevel: 51.00,
    dangerLevel: 52.00,
    highestFloodLevel: 53.85,
    highestFloodDate: '2016-08-25',
    gaugeDatum: 44.00,
    cwcStationCode: 'CWC-SON-MNR',
  },
  {
    id: 'station-shahdol',
    name: 'Shahdol / Jaisinghnagar (Sone River)',
    hindiName: 'शहडोल / जयसिंहनगर (सोन नदी)',
    river: 'Sone River',
    division: 'Shahdol Division',
    district: 'Shahdol',
    state: 'Madhya Pradesh',
    coordinates: {
      lat: 23.672,
      lng: 81.388,
    },
    warningLevel: 462.00,
    dangerLevel: 463.50,
    highestFloodLevel: 465.10,
    highestFloodDate: '2016-08-18',
    gaugeDatum: 440.00,
    cwcStationCode: 'CWC-SON-SHD',
  },
];

export const DEFAULT_PRIMARY_STATION_ID = 'station-rewa';
